import React from 'react';
import { MdFileDownload, MdPrint } from 'react-icons/md';
import { useSecurity } from '../../../context/SecurityContext';

function ExportFooter({ filteredCases, onExportPDF }) {
  const { session } = useSecurity();
  const refreshTime = new Date().toLocaleTimeString();

  // Real client-side CSV downloader of the filtered caseload
  const exportToCSV = (filename = 'ksp_filtered_statistics.csv') => {
    if (!filteredCases || filteredCases.length === 0) {
      alert('No data available to export.');
      return;
    }

    const headers = [
      'CaseMasterID',
      'CrimeNo',
      'RegisteredDate',
      'DistrictName',
      'PoliceStationName',
      'MajorHeadName',
      'MinorHeadName',
      'CaseStatus',
      'Severity'
    ];

    const rows = filteredCases.map(c => [
      c.CaseMasterID,
      c.CrimeNo,
      c.CrimeRegisteredDate,
      c.districtName,
      c.policeStationName,
      c.majorHeadName,
      c.minorHeadName,
      c.statusName,
      c.isHeinous ? 'Heinous' : 'Non-Heinous'
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.map(val => {
        const str = String(val || '').replace(/"/g, '""');
        return `"${str}"`;
      }).join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handlePrintPDF = () => {
    if (onExportPDF) {
      onExportPDF();
    } else {
      window.print();
    }
  };

  const userName = session && session.officerName ? session.officerName : 'DGP Kishore, IPS';
  const userRole = session && session.role ? session.role : 'State DGP Command';

  return (
    <div className="stats-footer-container" style={{
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: '30px',
      paddingTop: '20px',
      borderTop: '1px solid var(--border-color)',
      flexWrap: 'wrap',
      gap: '16px'
    }}>
      {/* Export Action Buttons */}
      <div style={{ display: 'flex', gap: '10px' }}>
        <button
          type="button"
          onClick={() => exportToCSV('ksp_filtered_statistics.csv')}
          style={{
            padding: '8px 14px',
            borderRadius: '6px',
            background: 'var(--bg-panel-alt)',
            border: '1px solid var(--border-color)',
            color: 'var(--text-primary)',
            fontSize: '12px',
            fontWeight: 600,
            display: 'flex',
            alignItems: 'center',
            gap: '6px',
            cursor: 'pointer'
          }}
          className="stats-btn"
        >
          <MdFileDownload size={16} />
          <span>Download CSV</span>
        </button>

        <button
          type="button"
          onClick={() => exportToCSV('ksp_filtered_statistics.xlsx')}
          style={{
            padding: '8px 14px',
            borderRadius: '6px',
            background: 'var(--bg-panel-alt)',
            border: '1px solid var(--border-color)',
            color: 'var(--text-primary)',
            fontSize: '12px',
            fontWeight: 600,
            display: 'flex',
            alignItems: 'center',
            gap: '6px',
            cursor: 'pointer'
          }}
          className="stats-btn"
        >
          <MdFileDownload size={16} />
          <span>Download Excel</span>
        </button>

        <button
          type="button"
          onClick={handlePrintPDF}
          style={{
            padding: '8px 14px',
            borderRadius: '6px',
            background: 'var(--bg-panel-alt)',
            border: '1px solid var(--border-color)',
            color: 'var(--text-primary)',
            fontSize: '12px',
            fontWeight: 600,
            display: 'flex',
            alignItems: 'center',
            gap: '6px',
            cursor: 'pointer'
          }}
          className="stats-btn"
        >
          <MdPrint size={16} />
          <span>Export PDF</span>
        </button>
      </div>

      {/* Metadata / Logged in Credentials */}
      <div style={{
        fontSize: '11px',
        color: 'var(--text-muted)',
        textAlign: 'right'
      }}>
        Data updated as of {refreshTime} · Generated by <strong>{userName}</strong> ({userRole})
      </div>

      <style>{`
        .stats-btn:hover {
          border-color: var(--accent-primary) !important;
          color: var(--accent-primary) !important;
        }
      `}</style>
    </div>
  );
}

export default ExportFooter;
